---
version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=james
      - PGID=james
      - TZ=Europe/London
    volumes:
      - /media/james/storage/dockerconfigs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
