---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=james
      - PGID=james
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /media/james/storage/dockerconfigs/jackett:/config
      - /media/james/storage/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
